# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDos', '0002_auto_20160601_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
